### ISSUE TITLE
Documentation is wrong for OPA Plugin

### ISSUE THREAD

**Issue by Parsifal-M** [Parsifal-M/brewed-backstage#49]
This part of the docs is no longer correct:

```
opa-client:
  opa:
    baseUrl: http://your-opa-server-url
    policies:
      catalog:
        package: your-catalog-package
```

It should actually be:

```
opa-client:
  opa:
    baseUrl: 'http://localhost:8181'
    policies:
      entityChecker: --> Entity checker plugin
        package: 'entitymeta'
      catalogPermission: --> Permission wrapper plugin
        package: 'catalog_policy'
```

Needs updating here: https://github.com/Parsifal-M/brewed-backstage/blob/main/plugins/opa-backend/README.md and could also be updated here: https://github.com/Parsifal-M/brewed-backstage/blob/main/plugins/opa-permissions-wrapper/README.md

Or atleast the back-end plugin should be the source of truth for it and we can just reference to that file in the wrapper plugin.
