### ISSUE TITLE
Update OPA config to be more dynamic

### ISSUE THREAD

**Issue by Parsifal-M** [Parsifal-M/brewed-backstage#63]
After speaking with Anders about integrating OPA with Backstage, a possible improvement would be to make the package name more dynamic.

I also had an idea while traveling that we could make the config accept an array of "configs" something like:

```yaml
opa-client:
  opa:
    baseUrl: 'http://localhost:8181/v1/data/opa/main'
    policies:
      plugin: entity-checker
        package: 'entitymeta'
      plugin: catalog-entity
        package: 'catalog_policy'
      plugin: some-other-plugin
        package: 'some-other-package'
```

We could then do something [here](https://github.com/Parsifal-M/brewed-backstage/blob/e7adc53c7625ab90f7807d083ffdc0e25938dba9/plugins/opa-permissions-wrapper/src/opa-evaluator/opaPermissionEvaluator.ts#L49C4-L49C4)

Which would make it more dynamic 🤔 💭 

Another option is to look at making a `main` package and then extending it as advised [here](https://styracommunity.slack.com/archives/D053AR06MMK/p1695806493282069)
